### ISSUE TITLE
Can we use English in the default README.md

### ISSUE THREAD

**Issue by hsluoyz** [nsnake/CasbinAdapter-Redis-Adapter#1]
Hi, I'm Casbin's author. Thanks for your contribution on this adapter!

I have added it into the official website: https://github.com/casbin/casbin-website/commit/2278b12359c642e1f3e9cdb7e1e7b4b484924177

Can you modify all Chinese text into English? So our international users/developers can also benefit from your code? Thanks!

**Comment by hsluoyz** [comment]
@nsnake

**Comment by nsnake** [comment]
have done.
